version: '3.7'
services:
  app:
    build: .
    ports:
      - "8888:${PORT}"
      - "2345:2345"
    volumes:
      - ./:/app
    working_dir: /app
    command: air -c .air.toml
    env_file:
      - ./.env