version: '3.7'
services:
  app:
    build: .
    ports:
      - "3000:8888"
      - "2345:2345"
    volumes:
      - ./:/app
    working_dir: /app
    command: air -c .air.toml
    env_file:
      - ./.env