// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"doc-api/api"
	"doc-api/env"
)

// Injectors from wire.go:

func InitializeServer() api.Server {
	port := env.NewPort()
	server := api.NewServer(port)
	return server
}
